
### ### ### auth route
POST http://localhost:3002/ide/run?language=cpp&compile=source
Content-Type: application/json

{
    "source": "60160027",
    "stdin" : "xxxxxx"
}

### ### ### auth route
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "60160027",
    "password" : "xxxxxx"
}



### ### ### auth route
GET http://localhost:3001/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjYwMTYwMDI3IiwiaWF0IjoxNjA4MDk0MTcxfQ.HtRaF9-4n54ed5_VbyTLp2nbviofmnFUkuuNIMwxw54


